require("plugins")
-- require("file-explorer")
require("mason-config")
require("pylsp")
-- require("code-completion")
require("custom-keys")
-- require("debugging")
-- require("styling")
require("file-finder")
require("syntax-highlight")
require("statusbar")